module.exports = {
  Admin: require("./admin.model"),
  Module: require("./module.model"),
  Permission: require("./permission.model"),
  Role:require('./role.model'),
  User: require('./user.model'),
  Document: require('./documents.model'),
  Testimonial: require('./testimonial.model'),
  GlobalSetting: require('./globalSetting.model'),
  Cart: require('./cart.model'),
  Wishlist: require('./wishlist.model'),
  Invoice: require('./invoices.model'),
  PaymentLog: require('./paymentLogs.model'),
  PurchaseOrder: require('./purchaseOrder.model'),
  EmailTemplate: require('./emailTemplate.model'),
  ReviewAndRating: require('./review.model'),
  Revenue: require('./revenue.model'),
  Blog: require('./blog.model'),
  
};